# Análisis de Ventas de Distribuidora

## 1. Objetivo del proyecto

## 2. Librerías

## 3. Configuración de Pandas

## 4. Rutas

## 5. Funciones de lectura y transformación

## 6. Carga de datos

## 7. Validación de carga
    - shape
    - info()
    - nulos
    - duplicados

## 8. Transformaciones de negocio
    - Importe Ajustado
    - Factor
    - Corrección de tipos de documento
    - Otras reglas del ERP

## 9. Modelado
    - merge clientes
    - merge vendedores
    - merge artículos
    - merge margen

## 10. Feature Engineering
    - columnas nuevas
    - KPIs
    - métricas

## 11. Exportación
    - parquet
    - csv
    - excel

In [1]:
# 2. Librerias
# Importa el módulo OS (Operating System) de Python
#Importa Path de la librería pathlib. Sirve para gestionar rutas de archivos y carpetas de forma inteligente, moderna y visual.
#Importa pandas, una biblioteca de Python para el análisis y manipulación de datos

import os
from pathlib import Path
import pandas as pd

In [2]:
# 3. Configuracion de Pandas
# Muestra todas las columnas sin límite
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#Si quiero desativar la opción de mostrar todas las columnas, puedo usar el siguiente comando:
#pd.reset_option('display.max_columns')
#pd.reset_option('display.max_rows')

In [3]:
# 4. Rutas

ruta_ventas_historicas = Path("../Ventas_Historico/Fuentes/Historico_Ventas")
ruta_margen_utilidad = Path("../Ventas_Historico/Fuentes/Historico_Margen")
ruta_maestros = Path("../Ventas_Historico/Fuentes/Maestros")

In [4]:
# 5. Funciones de lectura de archivos y transformacion

def leer_ventas(ruta):
    # Buscar dinámicamente todos los archivos xls que empiecen con "ventas_"
    rutas_archivos_ventas = list(ruta.glob("Ventas_*.xls"))

    #Lista para almacenar los DataFrames individuales
    lista_dataframes_ventas = []

    # Bucle para leer cada archivo encontrado de ventas y asignarle un numero que identifica de que archivo viene
    digito_archivo = 1
    for archivo in rutas_archivos_ventas:
        print(f"Leyendo de forma dinámica: {archivo.name}")

        # Leer el archivo actual y eliminar las primeras 18 filas. Ademas como tuve problemas por como pandas lee las fecha, le pido que a la columna "Fecha" me la devuelva
        # directamente como un str, y despues la voy a forzar a que tome el primer valor como dia.
        df = pd.read_excel(archivo, skiprows=18, engine="openpyxl", dtype={'Fecha': str})

        # La columna fecha es un str que viene del paso anterior, entonces le digo que tome el primer valor como dia, si no forzaba a la lectura como str pandas me convertia
        # los valores como fecha y a veces tomaba el primer valor como mes, y a veces como dia, al hacer el dayfirst ya estaba cambiado y no servia
        df["Fecha"] = pd.to_datetime(df["Fecha"], dayfirst=True, format="mixed", errors="coerce")

        partes_nombre = archivo.stem.split("_")  # Separa el nombre por guiones bajos
        
        # El valor del tipo de venta esta en la ultima posicion del nombre con -1 alcanzo ese valor
        tipo_venta = partes_nombre[-1]
        df["Tipo Venta"] = str(tipo_venta)  # Guarda 'blanco' o 'negro'
        lista_dataframes_ventas.append(df)

        #Asignacion de un digito en una nueva columna para identificar de que archivo salio el valor
        df["Archivo"] = digito_archivo
        digito_archivo = digito_archivo + 1
    
    # Concatenar todo solo si se encontraron archivos de ventas
    if lista_dataframes_ventas:
        df_ventas_total = pd.concat(lista_dataframes_ventas, axis=0, ignore_index=True)
        print("\n¡Todos los archivos de Ventas fueron concatenados con éxito!")
        #print(df_ventas_total.head(5))
    else:
        print("No se encontraron archivos de ventas en la carpeta.")

    return df_ventas_total

def leer_margenes(ruta):
    # Buscar dinámicamente todos los archivos xls que empiecen con "margen_"
    rutas_archivos_margen = list(ruta.glob("Margen_*.xls"))

    #Lista para almacenar los DataFrames individuales
    lista_dataframes_margen = []

    # Bucle para leer cada archivo encontrado de Margenes
    for archivo in rutas_archivos_margen:
        print(f"Leyendo de forma dinámica: {archivo.name}")

        # Leer el archivo actual y eliminar las primeras 5 filas  
        df = pd.read_excel(archivo, skiprows=5, engine="openpyxl")

        #Por ahora comento las transformaciones  
        # Opcional: Agregar columnas para saber de qué año y tipo proviene el dato
        # (Asumiendo nombres como 'ventas_2025_negro.csv')
        partes_nombre = archivo.stem.split("_")  # Separa el nombre por guiones bajos
        mes = partes_nombre[1]
        año = partes_nombre[2]
        tipo_venta = partes_nombre[3]
        df["Año"] = año
        df["Mes"] = mes
        df["Tipo Venta"] = tipo_venta

        lista_dataframes_margen.append(df)

    # Concatenar todo solo si se encontraron archivos de Margen
    if lista_dataframes_margen:
        df_margen_utilidad = pd.concat(lista_dataframes_margen, axis=0, ignore_index=True)
        print("\n¡Todos los archivos de Margenes fueron concatenados con éxito!")
        #print(df_margen_utilidad.head(5))
    else:
        print("No se encontraron archivos de Margen en la carpeta.")

    return df_margen_utilidad

def leer_articulos_clase(ruta):

    """ Lee el archivo "Maestro_Articulos_Clase.xls" y transforma el formato por bloques original en una tabla normalizada
    Parámetros:
    -----------

    ruta : pathlib.Path
        Carpeta donde se encuentra el archivo maestro

    Retorna
    -------

    pandas.DataFrame 
        DataFrame con los artículos, códigos de clase y descripción de clase
    """

    #El archivo que emite el sistema es un excel .xls con un formato por bloques y filas basura
    df_articulos_clase = pd.read_excel(ruta / "Maestro_Articulos_Clase.xls", engine="openpyxl")

    #Cada bloque comienza con una celda que identifica la clase
    filtro_clase = df_articulos_clase["Unnamed: 0"].str.startswith("Clas", na=False)

    df_articulos_clase.loc[filtro_clase, "Clase"] = (
        df_articulos_clase.loc[filtro_clase, "Unnamed: 0"]
    )

    #Aislado el dato de la clase se completan los valores
    df_articulos_clase["Clase"] = df_articulos_clase["Clase"].ffill()

    #Cada clase tiene una descripcion, se aisla el valor de descripcion de la clase
    df_articulos_clase["Descripcion"] = None
    filtro_clase = df_articulos_clase["Unnamed: 0"].str.startswith("Clase", na= False)
    df_articulos_clase.loc[filtro_clase, "Descripcion"] = df_articulos_clase.loc[filtro_clase, "Unnamed: 1"]

    #Una vez aislada la descripcion se completan los valores
    df_articulos_clase["Descripcion"] = df_articulos_clase["Descripcion"].ffill()

    #Como el archivo que exporta el sistema tiene filas basura es necesario eliminarlasy darle un nuevo formato
    #El archivo que exporta el sistema tiene 12 filas innecesarias
    df_articulos_clase.drop(df_articulos_clase.index[:12], inplace= True)
    df_articulos_clase.reset_index(drop = True, inplace = True)
    df_articulos_clase.columns = df_articulos_clase.iloc[0]
    df_articulos_clase = df_articulos_clase[1:].reset_index(drop=True)

    #Se acomodan los encabezados para darle forma al df
    df_articulos_clase = df_articulos_clase.dropna(subset=["Codigo"])

    #Se termina renombrando las celdas para que tengan un sentido
    df_articulos_clase.rename(
        columns={
            "Clase 1017": "Codigo Clase", "100 - EPICUREAN CHAMPAGNE - EPC - 40%" : "Descripcion Clase"
        },
        inplace= True
    )

    #Se realiza validacion para saber si funciono sin errores la funcion o si los archivos estan en la carpeta
    if df_articulos_clase.empty:
        raise ValueError("El DataFrame de artículos por clase quedó vacío.")
    else:
        print("Archivo de Articulos por cLases Listo")

    return df_articulos_clase

def leer_articulos_proveedor(ruta):

    """ Lee el archivo "Maestro_Articulos_Proveedor.xls" y transforma el formato por bloques original en una tabla normalizada
    Parámetros:
    -----------

    ruta : pathlib.Path
        Carpeta donde se encuentra el archivo maestro

    Retorna
    -------

    pandas.DataFrame 
        DataFrame con los artículos, códigos de clase y descripción de clase
    """
    #El archivo que emite el sistema es un excel .xls con un formato por bloques y filas basura
    df_articulos_proveedor = pd.read_excel(ruta / "Maestro_Articulos_Proveedor.xls", engine="openpyxl")

   #Cada bloque comienza con una celda que identifica al proveedor
    filtro_proveedor = df_articulos_proveedor["Unnamed: 0"].str.startswith("Prov", na=False)

    df_articulos_proveedor.loc[filtro_proveedor, "Proveedor"] = (
        df_articulos_proveedor.loc[filtro_proveedor, "Unnamed: 0"]
    )

    #Aislado el dato del proveedor se completan los valores
    df_articulos_proveedor["Proveedor"] = df_articulos_proveedor["Proveedor"].ffill()

    #Detecta descripciones
    df_articulos_proveedor["Descripcion"] = None
    filtro_proveedor = df_articulos_proveedor["Unnamed: 0"].str.startswith("Prove", na= False)
    df_articulos_proveedor.loc[filtro_proveedor, "Descripcion"] = df_articulos_proveedor.loc[filtro_proveedor, "Unnamed: 1"]

    #Completa descipciones
    df_articulos_proveedor["Descripcion"] = df_articulos_proveedor["Descripcion"].ffill()

    #Como el archivo que exporta el sistema tiene filas basura es necesario eliminarlas y darle un nuevo formato
    #El archivo que exporta el sistema tiene 14 filas innecesarias
    df_articulos_proveedor.drop(df_articulos_proveedor.index[:14], inplace= True)
    df_articulos_proveedor.reset_index(drop = True, inplace = True)
    df_articulos_proveedor.columns = df_articulos_proveedor.iloc[0]
    df_articulos_proveedor = df_articulos_proveedor[1:].reset_index(drop=True)

    #Se acomodan los encabezados para darle forma al df
    df_articulos_proveedor = df_articulos_proveedor.dropna(subset=["Codigo"])

    #Se termina renombrando las celdas para que tengan un sentido
    df_articulos_proveedor.rename(
        columns={
            "Proveedor 1": "Codigo Proveedor", "Patricio Prestamo" : "Descripcion Proveedor"
        },
        inplace= True
    )

    #Se realiza validacion para saber si funciono sin errores la funcion o si los archivos estan en la carpeta
    if df_articulos_proveedor.empty:
        raise ValueError("El DataFrame de artículos por proveedor quedó vacío.")
    else:
        print("Archivo de Articulos por Proveedor Listo")

    return df_articulos_proveedor

def leer_vendedores(ruta):
    df_vendedor = pd.read_excel(ruta / "Vendedores.xlsx", engine="openpyxl")
    return df_vendedor

def read_clients(path):
    df_clients = pd.read_excel(path / "Clientes.xls",skiprows=18, engine="openpyxl")
    return df_clients

In [5]:
# 6. Carga de Datos

df_ventas_total = leer_ventas(ruta_ventas_historicas)

df_margen_utilidad = leer_margenes(ruta_margen_utilidad)

df_articulos_clase = leer_articulos_clase(ruta_maestros)

df_articulos_proveedor = leer_articulos_proveedor(ruta_maestros)

df_vendedor = leer_vendedores(ruta_maestros)

df_clients = read_clients(ruta_maestros)

Leyendo de forma dinámica: Ventas_2025_B.xls
Leyendo de forma dinámica: Ventas_2025_N.xls
Leyendo de forma dinámica: Ventas_2026_06_B.xls
Leyendo de forma dinámica: Ventas_2026_06_N.xls
Leyendo de forma dinámica: Ventas_2026_07_B.xls
Leyendo de forma dinámica: Ventas_2026_07_N.xls
Leyendo de forma dinámica: Ventas_2026_B.xls
Leyendo de forma dinámica: Ventas_2026_N.xls

¡Todos los archivos de Ventas fueron concatenados con éxito!
Leyendo de forma dinámica: Margen_01_2025_B.xls
Leyendo de forma dinámica: Margen_01_2025_N.xls
Leyendo de forma dinámica: Margen_01_2026_B.xls
Leyendo de forma dinámica: Margen_01_2026_N.xls
Leyendo de forma dinámica: Margen_02_2025_B.xls
Leyendo de forma dinámica: Margen_02_2025_N.xls
Leyendo de forma dinámica: Margen_02_2026_B.xls
Leyendo de forma dinámica: Margen_02_2026_N.xls
Leyendo de forma dinámica: Margen_03_2025_B.xls
Leyendo de forma dinámica: Margen_03_2025_N.xls
Leyendo de forma dinámica: Margen_03_2026_B.xls
Leyendo de forma dinámica: Margen_03_2026_N.xls
Leyendo de forma dinámica: Margen_04_2025_B.xls
Leyendo de forma dinámica: Margen_04_2025_N.xls
Leyendo de forma dinámica: Margen_04_2026_B.xls
Leyendo de forma dinámica: Margen_04_2026_N.xls
Leyendo de forma dinámica: Margen_05_2025_B.xls
Leyendo de forma dinámica: Margen_05_2025_N.xls
Leyendo de forma dinámica: Margen_05_2026_B.xls
Leyendo de forma dinámica: Margen_05_2026_N.xls
Leyendo de forma dinámica: Margen_06_2025_B.xls
Leyendo de forma dinámica: Margen_06_2025_N.xls
Leyendo de forma dinámica: Margen_06_2026_B.xls
Leyendo de forma dinámica: Margen_06_2026_N.xls
Leyendo de forma dinámica: Margen_07_2025_B.xls
Leyendo de forma dinámica: Margen_07_2025_N.xls
Leyendo de forma dinámica: Margen_07_2026_B.xls
Leyendo de forma dinámica: Margen_07_2026_N.xls
Leyendo de forma dinámica: Margen_08_2025_B.xls
Leyendo de forma dinámica: Margen_08_2025_N.xls
Leyendo de forma dinámica: Margen_09_2025_B.xls
Leyendo de forma dinámica: Margen_09_2025_N.xls
Leyendo de forma dinámica: Margen_10_2025_B.xls
Leyendo de forma dinámica: Margen_10_2025_N.xls
Leyendo de forma dinámica: Margen_11_2025_B.xls
Leyendo de forma dinámica: Margen_11_2025_N.xls
Leyendo de forma dinámica: Margen_12_2024_N.xls
Leyendo de forma dinámica: Margen_12_2025_B.xls
Leyendo de forma dinámica: Margen_12_2025_N.xls

¡Todos los archivos de Margenes fueron concatenados con éxito!
Archivo de Articulos por cLases Listo
Archivo de Articulos por Proveedor Listo

In [6]:
# 7. Validación de carga

print(f"Ventas: {df_ventas_total.shape}")
print(f"Margen: {df_margen_utilidad.shape}")
#print(f"Clientes: {df_clientes.shape}")
print(f"Artículos Clase: {df_articulos_clase.shape}")
print(f"Artículos Proveedor: {df_articulos_proveedor.shape}")
print(f"Vendedores: {df_vendedor.shape}")

print("\nValores nulos:")
print(df_ventas_total.isna().sum())

print("\nDuplicados Ventas:")
print(df_ventas_total.duplicated().sum())

print("\nDuplicados Margenes:")
print(df_margen_utilidad.duplicated().sum())

print("\nDuplicados Articulos por Clase:")
print(df_articulos_clase.duplicated().sum())

print("\nDuplicados Articulos por Proveedor:")
print(df_articulos_proveedor.duplicated().sum())

print("\nTipos de datos:")
print(df_ventas_total.dtypes)

Ventas: (63936, 25)
Margen: (14573, 28)
Artículos Clase: (7605, 4)
Artículos Proveedor: (8546, 4)
Vendedores: (44, 4)

Valores nulos:
Codigo               0
Descripcion          0
Cantidad             0
Importe              0
Fecha                0
Doc                  0
Tipo                 0
Numero               0
xUnidad de Medida    0
-                    0
Cliente              0
Nombre               0
Razon Social         0
CUIT                 0
Documento            0
Vendedor             0
C.Postal             0
Localidad            0
Direccion            0
Estado Cta           0
P.Pago               0
Lista                0
Color                0
Tipo Venta           0
Archivo              0
dtype: int64

Duplicados Ventas:
27

Duplicados Margenes:
0

Duplicados Articulos por Clase:
0

Duplicados Articulos por Proveedor:
0

Tipos de datos:
Codigo                        int64
Descripcion                     str
Cantidad                    float64
Importe                     float64
Fecha                datetime64[us]
Doc                             str
Tipo                            str
Numero                        int64
xUnidad de Medida           float64
-                            object
Cliente                       int64
Nombre                          str
Razon Social                    str
CUIT                          int64
Documento                       str
Vendedor                        str
C.Postal                      int64
Localidad                       str
Direccion                    object
Estado Cta                      str
P.Pago                        int64
Lista                           str
Color                         int64
Tipo Venta                      str
Archivo                       int64
dtype: object

In [7]:
duplicados = df_ventas_total[df_ventas_total.duplicated(keep=False)]

#duplicados.sort_values(
#    ["Numero", "Codigo", "Fecha"]
#)

8. Transformaciones de negocio

In [8]:
#Los campos importe y cantidad se encuentran como un valor positivo, aunque el tipo de movimiento haya sido una facturacion "FAC" o nota de debito "NDE", o una nota de 
#credito "NCR" por esta razon se crea una columna factor con un valor 1 y que si el valor de "Doc" es "NCR" le asigna -1. Luego se agrega la columna "Importe Ajustado" y 
#"Cantidad Ajustada" que calculan el valor con el signo correspondiente para hacer calculos directos
df_ventas_total["Factor"] = 1
df_ventas_total.loc[df_ventas_total["Doc"] == "NCR", "Factor"] = -1
df_ventas_total["Importe Ajustado"] = df_ventas_total["Importe"] * df_ventas_total["Factor"]
df_ventas_total["Cantidad Ajustada"] = df_ventas_total["Cantidad"] * df_ventas_total["Factor"]
df_ventas_total["Año"] = df_ventas_total["Fecha"].dt.year.astype(str)
df_ventas_total["Mes"] = df_ventas_total["Fecha"].dt.strftime("%m")

In [9]:
#Se elimina duplicados que vienen de diferentes archivos, pero se dejan los que vienen dentro de un mismo archivo
columnas_comparacion = df_ventas_total.columns.drop("Archivo")
duplicados = df_ventas_total[
    df_ventas_total.duplicated(
        subset=columnas_comparacion,
        keep=False
    )
].copy()
columnas_comparacion = columnas_comparacion.tolist()
grupos = duplicados.groupby(columnas_comparacion)
filas_a_eliminar = []
for nombre, grupo in grupos:
    if grupo["Archivo"].nunique() > 1:
        grupo = grupo.sort_values("Archivo")
        filas_a_eliminar.append(grupo.iloc[1:])
filas_a_eliminar = pd.concat(filas_a_eliminar)
df_ventas_total = df_ventas_total.drop(index=filas_a_eliminar.index)

In [10]:
#Se enriquese el df de ventas con informacion de los demas df.

df_ventas_total = df_ventas_total.drop(columns=["Descripcion"], errors="ignore")

columnas_prov = [col for col in df_articulos_proveedor.columns if col != "Descripcion"]
df_ventas_total = df_ventas_total.merge(
    df_articulos_proveedor[columnas_prov],
    on="Codigo",
    how="left"
)

df_ventas_total = df_ventas_total.merge(
    df_articulos_clase,
    on="Codigo",
    how="left"
)

df_ventas_total = df_ventas_total.merge(
    df_vendedor.rename(columns={"Codigo": "Codigo Vendedor",
                                "Nombre": "Nombre Vendedor"}),
    left_on="Vendedor",
    right_on="Codigo Vendedor",
    how="left"
).drop(columns=["Vendedor"])


df_ventas_total = df_ventas_total.merge(
    df_clients[["Codigo", "Cliente"]],
    left_on="Cliente",
    right_on="Codigo",
    how="left",
    suffixes=("", "_eliminar")  # Deja intacto el 'Codigo' de la izquierda y renombra el de la derecha
).drop(columns=["Cliente_eliminar", "Codigo_eliminar"])  # Borra el código de los clientes que no querías

df_ventas_total = df_ventas_total.merge(
    df_margen_utilidad[["Año", "Mes", "Codigo", "Tipo Venta", "Margen"]],
    left_on=["Año", "Mes", "Codigo", "Tipo Venta"],
    right_on=["Año", "Mes", "Codigo", "Tipo Venta"],
    how= "left"
)

In [11]:
df_ventas_total = df_ventas_total.drop(columns=[
    "xUnidad de Medida",
    "-",
    "Color"
    ])
df_ventas_total = df_ventas_total.rename(columns=
                                         {"Codigo":"Codigo Articulo",
                                          "Nombre": "Nombre Cliente",
                                          "Descripcion": "Descripcion Articulo",
                                          "Margen": "Margen Utilidad"
                                          })

In [12]:
df_ventas_total.tail(10)

,Codigo Articulo,Cantidad,Importe,Fecha,Doc,Tipo,Numero,Cliente,Nombre Cliente,Razon Social,CUIT,Documento,C.Postal,Localidad,Direccion,Estado Cta,P.Pago,Lista,Tipo Venta,Archivo,Factor,Importe Ajustado,Cantidad Ajustada,Año,Mes,Codigo Proveedor,Descripcion Proveedor,Descripcion Articulo,Codigo Clase,Descripcion Clase,Codigo Vendedor,Nombre Vendedor,Zona,Estado,Margen Utilidad
84285,5070,2.0,375400.0,2026-05-28,FAC,B,9000101373,1,Consumidor Final,Foresta BCH,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,375400.0,2.0,2026,05,Proveedor 1743,Fruto De La Confianz,Nuez Mariposa Extra Light 10kg SIN TACC,Clase 110,279 - FRUTAS SECAS A GRANEL,BCHE-C,Paulo,Bariloche,Normal,26.55
84286,5917,1.0,19000.0,2026-05-28,FAC,B,9000101373,1,Consumidor Final,Foresta BCH,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,19000.0,1.0,2026,05,Proveedor 1577,Fruggina,Jugo CAJA Fruggina 12u de 500c MANZANA,Clase 229,214 - JUGOS FRUTALES Y PULPAS,BCHE-C,Paulo,Bariloche,Normal,34.15
84287,6838,1.0,19000.0,2026-05-28,FAC,B,9000101373,1,Consumidor Final,Foresta BCH,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,19000.0,1.0,2026,05,Proveedor 1577,Fruggina,Jugo CAJA Fruggina 12u de 500c MANZ VER,Clase 229,214 - JUGOS FRUTALES Y PULPAS,BCHE-C,Paulo,Bariloche,Normal,34.15
84288,5918,1.0,19000.0,2026-05-28,FAC,B,9000101373,1,Consumidor Final,Foresta BCH,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,19000.0,1.0,2026,05,Proveedor 1577,Fruggina,Jugo CAJA Fruggina 12u de 500c PERA,Clase 229,214 - JUGOS FRUTALES Y PULPAS,BCHE-C,Paulo,Bariloche,Normal,34.15
84289,7399,1.0,42300.0,2026-05-29,FAC,B,9000101374,1,Consumidor Final,Clara Vending,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,42300.0,1.0,2026,05,Proveedor 1804,Las Perdices,Gin Perdix London Dry 750,Clase 22,222 - GIN,MG Salon,Marcas Garage,NaN,Normal,28.38
84290,6376,2.0,24800.0,2026-05-29,FAC,B,9000101375,1,Consumidor Final,NY Cookies Sebastian,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,24800.0,2.0,2026,05,Proveedor 1151,Alyser X Fracc,Arandanos Deshidratados 1kg,Clase 78,263 - FRUTAS SECAS Y DESHIDRATADAS FRACCIONADAS,BCHE-C E,Gonzalo,Bariloche,Normal,29.66
84291,6510,1.0,35400.0,2026-05-29,FAC,B,9000101375,1,Consumidor Final,NY Cookies Sebastian,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,35400.0,1.0,2026,05,Proveedor 2031,Fenix,Cob. S/Amarg 62% - ECUADOR x1Kg FNX,Clase 34,306 - COBERTURAS - ALTO % CACAO SIN TACC,BCHE-C E,Gonzalo,Bariloche,Normal,26.50
84292,5274,1.0,22800.0,2026-05-29,FAC,B,9000101375,1,Consumidor Final,NY Cookies Sebastian,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,22800.0,1.0,2026,05,Proveedor 21,Alyser S.A.,Cob. S/Amarga - PICOS DEL SUR 1 kg,Clase 922,308 - COBERTURA DE CHOCOLATE - PICOS DEL SUR,BCHE-C E,Gonzalo,Bariloche,Normal,26.65
84293,6425,1.0,15800.0,2026-05-29,FAC,B,9000101375,1,Consumidor Final,NY Cookies Sebastian,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,15800.0,1.0,2026,05,Proveedor 1804,Las Perdices,Bag Pouch - Chac Chac Cab Franc x 2250cc,Clase 202,117 - LAS PERDICES - BAG IN BOX 50%,BCHE-C E,Gonzalo,Bariloche,Normal,28.52
84294,6425,1.0,15800.0,2026-05-29,FAC,B,9000101375,1,Consumidor Final,NY Cookies Sebastian,0,S/D,1,Indefinido,Uiutg,No Posee,0,Bche Distr,N,8,1,15800.0,1.0,2026,05,Proveedor 2090,Almacen De Vinos,Bag Pouch - Chac Chac Cab Franc x 2250cc,Clase 202,117 - LAS PERDICES - BAG IN BOX 50%,BCHE-C E,Gonzalo,Bariloche,Normal,28.52

In [13]:
cantidad_nan = df_ventas_total['Margen Utilidad'].isna().sum()

df_ventas_nan = df_ventas_total[df_ventas_total['Margen Utilidad'].isna()]

print(f"Total de filas vacías en Margen: {cantidad_nan}")

df_ventas_nan

Total de filas vacías en Margen: 780

      Codigo Articulo  Cantidad     Importe      Fecha  Doc Tipo      Numero  \
259              6678     1.000     8105.79 2025-01-02  FAC    A  1100004019
260              6820     1.000        0.00 2025-01-02  FAC    A  1100004019
1002             6678     1.000     8105.79 2025-01-06  NCR    A   500005282
1199             6678     1.000        0.00 2025-01-07  FAC    A  1100004043
1200             6820     1.000        0.00 2025-01-07  FAC    A  1100004043
1211             6678     1.000        0.00 2025-01-07  FAC    A  1100004044
1212             6820     1.000        0.00 2025-01-07  FAC    A  1100004044
1232             6678     1.000     8105.79 2025-01-07  NCR    A  1100000102
1233             6820     1.000        0.00 2025-01-07  NCR    A  1100000102
1244             6678     1.000        0.00 2025-01-07  NCR    A  1100000103
1245             6820     1.000        0.00 2025-01-07  NCR    A  1100000103
1248             6678     1.000     8105.79 2025-01-07  NDE    A   500000155
1554              831     2.000        0.00 2025-01-08  FAC    A  1100004050
2462             5427     6.000        0.00 2025-01-13  FAC    A   500056985
2463             5427     6.000        0.00 2025-01-13  FAC    A   500056985
2470             5427     6.000        0.00 2025-01-13  FAC    A   500056991
2471             5427     6.000        0.00 2025-01-13  FAC    A   500056991
2476             5427     6.000        0.00 2025-01-13  NCR    A   500005310
2477             5427     6.000        0.00 2025-01-13  NCR    A   500005310
2502             5427     6.000        0.00 2025-01-13  FAC    A   500056998
2503             5427     6.000        0.00 2025-01-13  FAC    A   500056998
2560             5427     6.000        0.00 2025-01-13  FAC    A   500056999
2561             5427     6.000        0.00 2025-01-13  FAC    A   500056999
2585             5427     6.000        0.00 2025-01-13  FAC    A   500057003
2586             5427     6.000        0.00 2025-01-13  FAC    A   500057003
2770             5427    12.000        0.00 2025-01-13  FAC    A   500056971
2771             5427    12.000        0.00 2025-01-13  FAC    A   500056971
2930              577     1.000    12602.82 2025-01-14  FAC    A   500057030
2932             6089     2.000    40065.84 2025-01-14  FAC    A   500057030
3362              577     1.000    12602.82 2025-01-15  NCR    A   500005328
3363             6089     2.000    40065.84 2025-01-15  NCR    A   500005328
3454             5427     6.000        0.00 2025-01-15  FAC    A   500057083
3455             5427     6.000        0.00 2025-01-15  FAC    A   500057083
3458             2997     1.000    60226.52 2025-01-15  FAC    A   500057091
3468             2997     1.000    60226.52 2025-01-15  NCR    A   500005329
3659             5427     6.000        0.00 2025-01-16  FAC    A   500057185
3660             5427     6.000        0.00 2025-01-16  FAC    A   500057185
3685             5427     6.000        0.00 2025-01-16  FAC    A   500057164
3686             5427     6.000        0.00 2025-01-16  FAC    A   500057164
3702             5427     6.000        0.00 2025-01-16  FAC    A   500057152
3703             5427     6.000        0.00 2025-01-16  FAC    A   500057152
3806             6830    24.000        0.00 2025-01-16  FAC    A   500057187
3817             5427     6.000        0.00 2025-01-16  FAC    A   500057184
3818             5427     6.000        0.00 2025-01-16  FAC    A   500057184
4049             6244     2.000        0.00 2025-01-20  FAC    A   700004653
4051             6283     1.000        0.00 2025-01-20  FAC    A   700004653
4061             6283     1.000        0.00 2025-01-20  FAC    A   700004654
4299             5427     6.000        0.00 2025-01-20  FAC    A   500057280
4300             5427     6.000        0.00 2025-01-20  FAC    A   500057280
4376             6830    24.000        0.00 2025-01-20  FAC    A   500057279
4388             5427     6.000        0.00 2025-01-20  FAC    A   500057281
4389             5427     6.000        0.00 2025-01-20  FAC    A   500057281
5071             6707     3.000    46119.15 2025-01-23  FAC    A  1100004156
5169             6707     3.000    46119.15 2025-01-24  NCR    A  1100000105
5621             6242     3.000    21356.05 2025-01-27  FAC    A   500057511
5637             6242     3.000    21356.05 2025-01-27  NCR    A   500005388
6023             6732     1.000        0.00 2025-01-29  FAC    A   700004678
6512               12    12.000   293999.94 2025-01-31  FAC    A   500057751
6513               12    12.000   293999.94 2025-01-31  FAC    A   500057751
6518               12    12.000   293999.94 2025-01-31  NCR    A   500005408
6519               12    12.000   293999.94 2025-01-31  NCR    A   500005408
6805             5423     1.000   167562.24 2025-02-03  FAC    A   500057817
7029             5423     1.000   167562.24 2025-02-04  NCR    A   500005421
7538             1953     1.000        0.00 2025-02-06  FAC    A   500058003
7663             5423     1.000   167562.24 2025-02-06  FAC    A   500057951
7672             5423     1.000   167562.24 2025-02-06  NCR    A   500005431
8072             5389     2.000     6822.20 2025-02-10  FAC    A  1100004253
8082             5389     2.000     6822.20 2025-02-10  NCR    A  1100000108
8108             6824     2.000    20469.72 2025-02-10  FAC    A  1100004256
8147             5427    12.000        0.00 2025-02-10  FAC    A   500058079
8148             5427    12.000        0.00 2025-02-10  FAC    A   500058079
8335             2513     3.000   189604.41 2025-02-10  FAC    A   500058083
8468             6824     2.000    20469.72 2025-02-11  NCR    A   500005451
8746             2513     3.000   189604.41 2025-02-12  NCR    A   500005459
9270             1953     1.000        0.00 2025-02-14  FAC    A   500058271
9626             1953     1.000        0.00 2025-02-17  FAC    A  1100004287
9630             1953     1.000        0.00 2025-02-17  FAC    A   500058306
9932             5377     1.000        0.00 2025-02-19  FAC    B   700012397
9936             5377     1.000        0.00 2025-02-19  FAC    B   700012400
9958             5377     1.000        0.00 2025-02-19  FAC    B   700012406
10047            6743     1.000        0.00 2025-02-19  FAC    A   700004731
10048            6743     1.000        0.00 2025-02-19  FAC    A   700004731
10137            1953     1.000        0.00 2025-02-19  FAC    A  1100004304
10139            1953     1.000        0.00 2025-02-19  FAC    A   500058408
10141            1953     1.000        0.00 2025-02-19  FAC    A   500058409
10146            1953     1.000        0.00 2025-02-19  FAC    A   500058410
10379            5377     2.000        0.00 2025-02-21  FAC    B   700012416
10558            6831    24.000        0.00 2025-02-21  FAC    A   500058503
10752            6831    24.000        0.00 2025-02-24  FAC    A   500058570
10773            1953     1.000        0.00 2025-02-24  FAC    A   500058539
10779            1953     1.000        0.00 2025-02-24  FAC    A   500058566
10802            6831    24.000        0.00 2025-02-24  FAC    A   500058549
10854            6831    24.000        0.00 2025-02-25  FAC    A   500058584
10897            6831    24.000        0.00 2025-02-25  FAC    A   500058585
11246            6761     1.000    69630.63 2025-02-26  FAC    A   500058620
11254            1953     1.000        0.00 2025-02-26  FAC    A   500058648
11367            6761     1.000    69630.63 2025-02-27  NCR    A   500005506
11595            5377     1.000        0.00 2025-02-27  FAC    B   700012441
11976              30     6.000    29625.00 2025-03-05  FAC    A   500058773
11977              30     6.000    29625.00 2025-03-05  FAC    A   500058773
11998            6813     1.000        0.00 2025-03-05  FAC    A   500058791
12020            6772     1.000    41803.08 2025-03-05  FAC    A   500058797
12124            4594     1.000    24101.90 2025-03-05  FAC    A   500058774
12126            4594     1.000    24101.90 2025-03-05  NCR    A   500005514
12308            4594     1.000    24101.90 2025-03-06  FAC    A   500058818
12391            6824     2.000    20469.72 2025-03-06  FAC    A  1100004379
12465            6363     2.000    13773.92 2025-03-06  FAC    B   500008143
12484            6363     2.000    13773.92 2025-03-06  NCR    B   500000753
12609            4594     1.000    24101.90 2025-03-07  NCR    A   500005517
12642            6772     1.000    41803.08 2025-03-07  NCR    A   500005518
12658            6813     1.000        0.00 2025-03-07  FAC    A   500058881
12687            5502     1.000        0.00 2025-03-10  FAC    B   500008149
12948            5427     6.000        0.00 2025-03-11  FAC    A   500058983
12949            5427     6.000        0.00 2025-03-11  FAC    A   500058983
12950            6828     6.000        0.00 2025-03-11  FAC    A   500058983
13080            6824     2.000    20469.72 2025-03-11  NCR    A  1100000111
13253              30     6.000    29625.00 2025-03-12  FAC    A   500059013
13254              30     6.000    29625.00 2025-03-12  FAC    A   500059013
13259              30     6.000    29625.00 2025-03-12  NCR    A   500005533
13260              30     6.000    29625.00 2025-03-12  NCR    A   500005533
13292              30     6.000    29625.00 2025-03-12  NCR    A   500005535
13293              30     6.000    29625.00 2025-03-12  NCR    A   500005535
13679             456     1.000   272976.96 2025-03-17  FAC    A   500059089
13680             456     1.000   272976.96 2025-03-17  FAC    A   500059089
13934             456     1.000   272976.96 2025-03-18  NCR    A   500005547
13935             456     1.000   272976.96 2025-03-18  NCR    A   500005547
14041            5502     1.000        0.00 2025-03-19  FAC    B  1100000361
14523            6253     2.000        0.00 2025-03-25  FAC    A   500059259
14999            4083     1.000    37743.97 2025-03-27  FAC    A   500059351
15243            4083     1.000    37743.97 2025-03-28  NCR    A   500005558
15311            5661     2.000        0.00 2025-03-29  FAC    A   700004817
15432            6253     1.000        0.00 2025-03-31  FAC    A   500059424
15632            6452    12.000        0.00 2025-04-01  FAC    A  1100004457
16073            6824     2.000    20487.04 2025-04-04  FAC    A   500059503
16075            6824     2.000    20487.04 2025-04-04  NCR    A   500005562
16298            6045     6.000   150876.00 2025-04-08  FAC    B  1100000369
16299            6055     6.000   111061.50 2025-04-08  FAC    B  1100000369
16422            6045     6.000   150876.00 2025-04-09  NCR    B   700000372
16423            6055     6.000   111061.50 2025-04-09  NCR    B   700000372
16609            6309    15.000        0.00 2025-04-10  FAC    A   500059625
16784            5820     6.000        0.00 2025-04-11  FAC    B   500008210
16786            6791     1.000        0.00 2025-04-11  FAC    B   500008210
17166            6819     2.000    17562.86 2025-04-14  FAC    A   500059661
17206            6819     2.000    17562.86 2025-04-15  NCR    A   500005578
18995            6666     2.000        0.00 2025-05-02  FAC    A   500060053
19119            6604     1.000        0.00 2025-05-05  FAC    A   500060105
19120            6606     1.000        0.00 2025-05-05  FAC    A   500060105
19121            6607     1.000        0.00 2025-05-05  FAC    A   500060105
19958            6407     2.000        0.00 2025-05-12  FAC    A   700004921
20189            6666     1.000    29745.28 2025-05-14  FAC    A   500060254
20190            6666     1.000    29745.28 2025-05-14  NCR    A   500005622
20224            5377     1.000        0.00 2025-05-14  FAC    B   700012852
20525            6604     2.000        0.00 2025-05-19  FAC    A   500060325
20526            6607     2.000        0.00 2025-05-19  FAC    A   500060325
20689            5372     6.000        0.00 2025-05-20  FAC    A   700004931
20725            6604     1.000        0.00 2025-05-20  FAC    A   500060344
20726            6607     3.000        0.00 2025-05-20  FAC    A   500060344
20729            6604     1.000        0.00 2025-05-20  FAC    A   500060345
20730            6607     2.000        0.00 2025-05-20  FAC    A   500060345
20731            6606     1.000        0.00 2025-05-20  FAC    A   500060345
20734            6604     2.000        0.00 2025-05-20  NCR    A   500005630
20735            6607     2.000        0.00 2025-05-20  NCR    A   500005630
20738            6604     1.000        0.00 2025-05-20  NCR    A   500005631
20739            6607     3.000        0.00 2025-05-20  NCR    A   500005631
20928            6407     3.000        0.00 2025-05-21  FAC    A   700004935
20970            6606     1.000        0.00 2025-05-22  FAC    A   500060396
20971            6607     1.000        0.00 2025-05-22  FAC    A   500060396
21149             343     4.000    78067.56 2025-05-23  FAC    A   500060415
21516            6694     2.000   114114.96 2025-05-27  FAC    B  1100000396
21518             219     2.000    36965.04 2025-05-27  FAC    B  1100000396
21520             221     2.000    36467.28 2025-05-27  FAC    B  1100000396
21521            6309     3.000    15961.65 2025-05-27  FAC    B  1100000396
21522            6648     3.000    15961.65 2025-05-27  FAC    B  1100000396
21523            6744     3.000    20773.68 2025-05-27  FAC    B  1100000396
21531            6694     2.000   114114.96 2025-05-27  NCR    B  1100000024
21533             219     2.000    36965.04 2025-05-27  NCR    B  1100000024
21535             221     2.000    36467.28 2025-05-27  NCR    B  1100000024
21536            6309     3.000    15961.65 2025-05-27  NCR    B  1100000024
21537            6648     3.000    15961.65 2025-05-27  NCR    B  1100000024
21538            6744     3.000    20773.68 2025-05-27  NCR    B  1100000024
21556             343     4.000    78067.56 2025-05-27  NCR    A   500005641
21615            4083     1.000    46676.60 2025-05-28  FAC    A   500060498
21696            6694     2.000   114114.96 2025-05-29  FAC    B   500008277
21698             219     2.000    36965.04 2025-05-29  FAC    B   500008277
21700             221     2.000    36467.28 2025-05-29  FAC    B   500008277
21701            6309     3.000    15961.65 2025-05-29  FAC    B   500008277
21702            6648     3.000    15961.65 2025-05-29  FAC    B   500008277
21703            6744     3.000    20773.68 2025-05-29  FAC    B   500008277
21710            6694     2.000   114114.96 2025-05-29  NCR    B   500000760
21712             219     2.000    36965.04 2025-05-29  NCR    B   500000760
21714             221     2.000    36467.28 2025-05-29  NCR    B   500000760
21715            6309     3.000    15961.65 2025-05-29  NCR    B   500000760
21716            6648     3.000    15961.65 2025-05-29  NCR    B   500000760
21717            6744     3.000    20773.68 2025-05-29  NCR    B   500000760
21929            4083     1.000    46676.60 2025-05-30  NCR    A   500005646
22045            2322     1.000   491024.78 2025-06-02  FAC    A   500060586
22182            6452     6.000        0.00 2025-06-03  FAC    B  1100000398
22185            6290    12.000        0.00 2025-06-03  FAC    B   500008280
22186            6262    12.000        0.00 2025-06-03  FAC    B   500008280
22189            6452     6.000        0.00 2025-06-03  FAC    B   500008280
22234            2322     1.000   491024.78 2025-06-03  NCR    A   500005652
22282            4083     1.000    46676.60 2025-06-04  FAC    A   500060622
22291            4083     1.000    46676.60 2025-06-04  NCR    A   500005657
22367            5372     1.000        0.00 2025-06-05  FAC    A   700004964
22401            6290    12.000        0.00 2025-06-05  FAC    B   500008282
22402            6262     6.000        0.00 2025-06-05  FAC    B   500008282
22405            6452     6.000        0.00 2025-06-05  FAC    B   500008282
22408            6290    12.000        0.00 2025-06-05  NCR    B   500000761
22409            6262    12.000        0.00 2025-06-05  NCR    B   500000761
22412            6452     6.000        0.00 2025-06-05  NCR    B   500000761
22782            4594     1.000    32896.35 2025-06-09  FAC    A   500060679
23207            4594     1.000    32896.35 2025-06-12  NCR    A   500005668
23998              26     6.000    30217.50 2025-06-18  FAC    A   500060951
23999              26     6.000    30217.50 2025-06-18  FAC    A   500060951
24000              26     6.000    30217.50 2025-06-18  NCR    A   500005680
24001              26     6.000    30217.50 2025-06-18  NCR    A   500005680
24028            4646     1.000    33923.85 2025-06-18  FAC    A   500060925
24449            4646     1.000    33923.85 2025-06-23  FAC    A   500061024
24470            4646     3.000   101771.55 2025-06-23  NCR    A   500005684
24529            7008     6.000   113080.82 2025-06-23  FAC    A   500060987
24530            7008     6.000   113080.82 2025-06-23  FAC    A   500060987
24609            5372     6.000    50620.71 2025-06-23  FAC    A   500061012
24680            7008     6.000   113080.82 2025-06-24  NCR    A   500005686
24681            7008     6.000   113080.82 2025-06-24  NCR    A   500005686
24726            4646     1.000    33923.85 2025-06-24  FAC    A   500061046
25300            6621     1.000    30188.90 2025-06-27  FAC    A  1100004703
25301            6621     1.000    30188.90 2025-06-27  NCR    A  1100000117
25571            5372     6.000    50620.71 2025-06-30  NCR    A   500005694
25598            7013     2.000        0.00 2025-07-01  FAC    A  1100004711
25600            7014     2.000        0.00 2025-07-01  FAC    A  1100004711
25687            6754     6.000        0.00 2025-07-01  FAC    A   500061271
25885            6164     1.000    19193.00 2025-07-03  FAC    B  1100000415
26337            6164     1.000    19193.00 2025-07-04  NCR    B  1100000027
26838            6261    12.000        0.00 2025-07-08  FAC    B   500008349
26840            6262    12.000        0.00 2025-07-08  FAC    B   500008349
26900            5364    24.000   202482.85 2025-07-08  FAC    A   500061491
27524            6164     1.000    19193.00 2025-07-14  FAC    B  1100000436
27536            6164     1.000    19193.00 2025-07-14  NCR    B  1100000029
28216            5364    24.000   202482.85 2025-07-16  NCR    A   500005730
28376            2513     1.000    65698.32 2025-07-16  FAC    A   500061785
28461            6309    12.000        0.00 2025-07-17  FAC    A   500061836
29123            6179     1.000        0.00 2025-07-22  FAC    A   500061987
29130            6179     1.000        0.00 2025-07-22  FAC    A   500061993
29138            6179     1.000        0.00 2025-07-22  NCR    A   500005741
29157            5502     2.000        0.00 2025-07-22  FAC    A   500061990
29173            2513     1.000    65698.32 2025-07-22  NCR    A   500005742
29193            6262     6.000        0.00 2025-07-22  FAC    A  1100004883
29198            6179     1.000        0.00 2025-07-22  FAC    A   500061996
29201            5502     2.000        0.00 2025-07-22  FAC    A   500061996
29212            2574     6.000        0.00 2025-07-22  FAC    A   500061997
29214            6261     6.000        0.00 2025-07-22  FAC    A   500061997
29309            3333     1.000        0.00 2025-07-22  FAC    A   500061988
29313            5436     3.000        0.00 2025-07-22  FAC    A   500061988
30566            7016     1.000    13299.99 2025-07-30  FAC    A   700005103
30593            5791     1.000    24479.98 2025-07-30  FAC    B   700013219
30599            5791     1.000    24479.98 2025-07-30  NCR    B   700000386
30799            7016     1.000    13299.99 2025-07-31  NCR    A   700000299
31057            6598     1.000    26650.78 2025-08-01  FAC    A  1100004957